{{include:amplitudeModifier/listing.js}}
{{include:bitcrusher/listing.js}}
{{include:momentaryAmplitudeMeter/listing.js}}
{{include:whiteNoiseGenerator/listing.js}}
{{include:sigmoid/listing.js}}
{{include:lagProcessor/listing.js}}
{{include:stableAmplitudeGenerator/listing.js}}
{{include:gain/listing.js}}
{{include:nothing/listing.js}}