#!/usr/bin/env python3

import sys, os, re

if len(sys.argv) < 3:
    print('input or output file missing')
    exit()



def includer(location, parentFile, inputfileName, outputObject, spacer=''):
    if(inputfileName == '*'):
        try:
            for item in os.listdir(location):
                if parentFile != item:
                    includer(location, parentFile, item, outputObject, spacer)
        except FileNotFoundError:
            print('Could not find file')
            print('\tlocation:', location)
            print('\tparentFile:', parentFile)
            print('\tinputfileName:', inputfileName)
            print('\t('+location+'/'+inputfileName+')')
            print()
            print('\terror:', sys.exc_info())
            exit(1)
    elif(inputfileName[0] == '.'):
        pass
    else:
        if os.path.isdir(location+'/'+inputfileName):
            includer( location+'/'+inputfileName+'/', '', '*', outputObject, spacer)
        else:
            try:
                inputFile = open(location+'/'+inputfileName)
            except FileNotFoundError:
                print('Could not find file')
                print('\tlocation:', location)
                print('\tparentFile:', parentFile)
                print('\tinputfileName:', inputfileName)
                print('\t(I was looking for '+location+'/'+inputfileName+')')
                print()
                print('\terror:', sys.exc_info())
                exit(1)

            for originalLine in inputFile:
                start = originalLine.find('{{')
                end = originalLine.find('}}')
                if( start != -1 and end != -1 ):
                    potentialSpacer = originalLine[:len(originalLine)-len(originalLine.lstrip())]
                    line = originalLine.strip()
                    if line[:2] == '//': continue
                    line = line.split('{{')[1].split('}}')[0].split(':')

                    if 'include' in line[0] and len(line) > 1:
                        newLocation = '/'.join((location+'/'+line[1]).split('/')[:-1])
                        newFile = line[1].split('/')[-1]
                        includer( newLocation, inputfileName, newFile, outputObject, spacer+potentialSpacer)
                    elif len(line) == 1:
                        print('Incorrect use of "include" keyword')
                        print('\tlocation:', location)
                        print('\tparentFile:', parentFile)
                        print('\tinputfileName:', inputfileName)
                        print('\toffending line:', originalLine)
                        exit(1)

                else:
                    outputObject.write(spacer+originalLine)

            outputObject.write('\n')
            inputFile.close()


tmp = sys.argv[1].rsplit('/', 1)
rootLocation = tmp[0]
inputfileName = tmp[1]
outputfileName = sys.argv[2]
outputFile = open(outputfileName,"w")

includer( rootLocation, None, inputfileName, outputFile )
# includer( os.getcwd(), None, inputfileName, outputFile )

outputFile.close()