this.menubar.styleLibrary.default = {};
this.menubar.styleLibrary.default.normal = {
    backgroundColour:{r:240/255,g:240/255,b:240/255,a:1},
    
    text__font:'Helvetica',
    text__fontSize:14,
    text__spacing:0.3,
    text__interCharacterSpacing:0.04,

    text_colour__off:                                  {r:0.2,g:0.2,b:0.2,a:1},
    text_colour__up:                                   {r:0.2,g:0.2,b:0.2,a:1},
    text_colour__press:                                {r:0.2,g:0.2,b:0.2,a:1},
    text_colour__select:                               {r:0.2,g:0.2,b:0.2,a:1},
    text_colour__select_press:                         {r:0.2,g:0.2,b:0.2,a:1},
    text_colour__glow:                                 {r:0.2,g:0.2,b:0.2,a:1},
    text_colour__glow_press:                           {r:0.2,g:0.2,b:0.2,a:1},
    text_colour__glow_select:                          {r:0.2,g:0.2,b:0.2,a:1},
    text_colour__glow_select_press:                    {r:0.2,g:0.2,b:0.2,a:1},
    text_colour__hover:                                {r:0.2,g:0.2,b:0.2,a:1},
    text_colour__hover_press:                          {r:0.2,g:0.2,b:0.2,a:1},
    text_colour__hover_select:                         {r:0.2,g:0.2,b:0.2,a:1},
    text_colour__hover_select_press:                   {r:0.2,g:0.2,b:0.2,a:1},
    text_colour__hover_glow:                           {r:0.2,g:0.2,b:0.2,a:1},
    text_colour__hover_glow_press:                     {r:0.2,g:0.2,b:0.2,a:1},
    text_colour__hover_glow_select:                    {r:0.2,g:0.2,b:0.2,a:1},
    text_colour__hover_glow_select_press:              {r:0.2,g:0.2,b:0.2,a:1},
        
    item_backing__off__colour:                              {r:180/255,g:180/255,b:180/255,a:1},
    item_backing__off__lineColour:                          {r:0/255,g:0/255,b:0/255,a:0},
    item_backing__off__lineThickness:                       0,
    item_backing__up__colour:                               {r:240/255,g:240/255,b:240/255,a:1},
    item_backing__up__lineColour:                           {r:0/255,g:0/255,b:0/255,a:0},
    item_backing__up__lineThickness:                        0,
    item_backing__press__colour:                            {r:240/255,g:240/255,b:240/255,a:1},
    item_backing__press__lineColour:                        {r:0/255,g:0/255,b:0/255,a:0},
    item_backing__press__lineThickness:                     0,
    item_backing__select__colour:                           {r:220/255,g:220/255,b:220/255,a:1},
    item_backing__select__lineColour:                       {r:0/255,g:0/255,b:0/255,a:0},
    item_backing__select__lineThickness:                    0,
    item_backing__select_press__colour:                     {r:229/255,g:167/255,b:255/255,a:1},
    item_backing__select_press__lineColour:                 {r:0,g:0,b:0,a:0},
    item_backing__select_press__lineThickness:              0,
    item_backing__glow__colour:                             {r:220/255,g:220/255,b:220/255,a:1},
    item_backing__glow__lineColour:                         {r:0/255,g:0/255,b:0/255,a:0},
    item_backing__glow__lineThickness:                      0,
    item_backing__glow_press__colour:                       {r:250/255,g:250/255,b:250/255,a:1},
    item_backing__glow_press__lineColour:                   {r:0/255,g:0/255,b:0/255,a:0},
    item_backing__glow_press__lineThickness:                0,
    item_backing__glow_select__colour:                      {r:220/255,g:220/255,b:220/255,a:1},
    item_backing__glow_select__lineColour:                  {r:120/255,g:120/255,b:120/255,a:1},
    item_backing__glow_select__lineThickness:               0,
    item_backing__glow_select_press__colour:                {r:250/255,g:250/255,b:250/255,a:1},
    item_backing__glow_select_press__lineColour:            {r:120/255,g:120/255,b:120/255,a:1},
    item_backing__glow_select_press__lineThickness:         0,
    item_backing__hover__colour:                            {r:229/255,g:167/255,b:255/255,a:1},
    item_backing__hover__lineColour:                        {r:0/255,g:0/255,b:0/255,a:0},
    item_backing__hover__lineThickness:                     0,
    item_backing__hover_press__colour:                      {r:240/255,g:240/255,b:240/255,a:1},
    item_backing__hover_press__lineColour:                  {r:0/255,g:0/255,b:0/255,a:0},
    item_backing__hover_press__lineThickness:               0,
    item_backing__hover_select__colour:                     {r:239/255,g:209/255,b:255/255,a:1},
    item_backing__hover_select__lineColour:                 {r:120/255,g:120/255,b:120/255,a:1},
    item_backing__hover_select__lineThickness:              0,
    item_backing__hover_select_press__colour:               {r:240/255,g:240/255,b:240/255,a:1},
    item_backing__hover_select_press__lineColour:           {r:120/255,g:120/255,b:120/255,a:1},
    item_backing__hover_select_press__lineThickness:        0,
    item_backing__hover_glow__colour:                       {r:239/255,g:209/255,b:255/255,a:1},
    item_backing__hover_glow__lineColour:                   {r:0/255,g:0/255,b:0/255,a:0},
    item_backing__hover_glow__lineThickness:                0,
    item_backing__hover_glow_press__colour:                 {r:250/255,g:250/255,b:250/255,a:1},
    item_backing__hover_glow_press__lineColour:             {r:0/255,g:0/255,b:0/255,a:0},
    item_backing__hover_glow_press__lineThickness:          0,
    item_backing__hover_glow_select__colour:                {r:240/255,g:240/255,b:240/255,a:1},
    item_backing__hover_glow_select__lineColour:            {r:120/255,g:120/255,b:120/255,a:1},
    item_backing__hover_glow_select__lineThickness:         0,
    item_backing__hover_glow_select_press__colour:          {r:250/255,g:250/255,b:250/255,a:1},
    item_backing__hover_glow_select_press__lineColour:      {r:120/255,g:120/255,b:120/255,a:1},
    item_backing__hover_glow_select_press__lineThickness:   0,

    checkbox_checkColour:{r:0.7,g:0.7,b:0.7,a:1}, 
};
const important_style_blending_colour = {r:1,g:0.75,b:0.75,a:1};
this.menubar.styleLibrary.default.important = {
    backgroundColour:{r:240/255,g:240/255,b:240/255,a:1},

    text__font:'Helvetica',
    text__fontSize:14,
    text__spacing:0.3,
    text__interCharacterSpacing:0.04,

    text_colour__off:                                  {r:0.2,g:0.2,b:0.2,a:1},
    text_colour__up:                                   {r:0.2,g:0.2,b:0.2,a:1},
    text_colour__press:                                {r:0.2,g:0.2,b:0.2,a:1},
    text_colour__select:                               {r:0.2,g:0.2,b:0.2,a:1},
    text_colour__select_press:                         {r:0.2,g:0.2,b:0.2,a:1},
    text_colour__glow:                                 {r:0.2,g:0.2,b:0.2,a:1},
    text_colour__glow_press:                           {r:0.2,g:0.2,b:0.2,a:1},
    text_colour__glow_select:                          {r:0.2,g:0.2,b:0.2,a:1},
    text_colour__glow_select_press:                    {r:0.2,g:0.2,b:0.2,a:1},
    text_colour__hover:                                {r:0.2,g:0.2,b:0.2,a:1},
    text_colour__hover_press:                          {r:0.2,g:0.2,b:0.2,a:1},
    text_colour__hover_select:                         {r:0.2,g:0.2,b:0.2,a:1},
    text_colour__hover_select_press:                   {r:0.2,g:0.2,b:0.2,a:1},
    text_colour__hover_glow:                           {r:0.2,g:0.2,b:0.2,a:1},
    text_colour__hover_glow_press:                     {r:0.2,g:0.2,b:0.2,a:1},
    text_colour__hover_glow_select:                    {r:0.2,g:0.2,b:0.2,a:1},
    text_colour__hover_glow_select_press:              {r:0.2,g:0.2,b:0.2,a:1},
        
    item_backing__off__colour:                              _canvas_.library.math.blendColours(this.menubar.styleLibrary.default.normal.item_backing__off__colour, important_style_blending_colour, 0.5),
    item_backing__off__lineColour:                          _canvas_.library.math.blendColours(this.menubar.styleLibrary.default.normal.item_backing__off__lineColour, important_style_blending_colour, 0.5),
    item_backing__off__lineThickness:                       0,
    item_backing__up__colour:                               _canvas_.library.math.blendColours(this.menubar.styleLibrary.default.normal.item_backing__up__colour, important_style_blending_colour, 0.5),
    item_backing__up__lineColour:                           _canvas_.library.math.blendColours(this.menubar.styleLibrary.default.normal.item_backing__up__lineColour, important_style_blending_colour, 0.5),
    item_backing__up__lineThickness:                        0,
    item_backing__press__colour:                            _canvas_.library.math.blendColours(this.menubar.styleLibrary.default.normal.item_backing__press__colour, important_style_blending_colour, 0.5),
    item_backing__press__lineColour:                        _canvas_.library.math.blendColours(this.menubar.styleLibrary.default.normal.item_backing__press__lineColour, important_style_blending_colour, 0.5),
    item_backing__press__lineThickness:                     0,
    item_backing__select__colour:                           _canvas_.library.math.blendColours(this.menubar.styleLibrary.default.normal.item_backing__select__colour, important_style_blending_colour, 0.5),
    item_backing__select__lineColour:                       _canvas_.library.math.blendColours(this.menubar.styleLibrary.default.normal.item_backing__select__lineColour, important_style_blending_colour, 0.5),
    item_backing__select__lineThickness:                    0,
    item_backing__select_press__colour:                     _canvas_.library.math.blendColours(this.menubar.styleLibrary.default.normal.item_backing__select_press__colour, important_style_blending_colour, 0.5),
    item_backing__select_press__lineColour:                 _canvas_.library.math.blendColours(this.menubar.styleLibrary.default.normal.item_backing__select_press__lineColour, important_style_blending_colour, 0.5),
    item_backing__select_press__lineThickness:              0,
    item_backing__glow__colour:                             _canvas_.library.math.blendColours(this.menubar.styleLibrary.default.normal.item_backing__glow__colour, important_style_blending_colour, 0.5),
    item_backing__glow__lineColour:                         _canvas_.library.math.blendColours(this.menubar.styleLibrary.default.normal.item_backing__glow__lineColour, important_style_blending_colour, 0.5),
    item_backing__glow__lineThickness:                      0,
    item_backing__glow_press__colour:                       _canvas_.library.math.blendColours(this.menubar.styleLibrary.default.normal.item_backing__glow_press__colour, important_style_blending_colour, 0.5),
    item_backing__glow_press__lineColour:                   _canvas_.library.math.blendColours(this.menubar.styleLibrary.default.normal.item_backing__glow_press__lineColour, important_style_blending_colour, 0.5),
    item_backing__glow_press__lineThickness:                0,
    item_backing__glow_select__colour:                      _canvas_.library.math.blendColours(this.menubar.styleLibrary.default.normal.item_backing__glow_select__colour, important_style_blending_colour, 0.5),
    item_backing__glow_select__lineColour:                  _canvas_.library.math.blendColours(this.menubar.styleLibrary.default.normal.item_backing__glow_select__lineColour, important_style_blending_colour, 0.5),
    item_backing__glow_select__lineThickness:               0,
    item_backing__glow_select_press__colour:                _canvas_.library.math.blendColours(this.menubar.styleLibrary.default.normal.item_backing__glow_select_press__colour, important_style_blending_colour, 0.5),
    item_backing__glow_select_press__lineColour:            _canvas_.library.math.blendColours(this.menubar.styleLibrary.default.normal.item_backing__glow_select_press__lineColour, important_style_blending_colour, 0.5),
    item_backing__glow_select_press__lineThickness:         0,
    item_backing__hover__colour:                            _canvas_.library.math.blendColours(this.menubar.styleLibrary.default.normal.item_backing__hover__colour, important_style_blending_colour, 0.5),
    item_backing__hover__lineColour:                        _canvas_.library.math.blendColours(this.menubar.styleLibrary.default.normal.item_backing__hover__lineColour, important_style_blending_colour, 0.5),
    item_backing__hover__lineThickness:                     0,
    item_backing__hover_press__colour:                      _canvas_.library.math.blendColours(this.menubar.styleLibrary.default.normal.item_backing__hover_press__colour, important_style_blending_colour, 0.5),
    item_backing__hover_press__lineColour:                  _canvas_.library.math.blendColours(this.menubar.styleLibrary.default.normal.item_backing__hover_press__lineColour, important_style_blending_colour, 0.5),
    item_backing__hover_press__lineThickness:               0,
    item_backing__hover_select__colour:                     _canvas_.library.math.blendColours(this.menubar.styleLibrary.default.normal.item_backing__hover_select__colour, important_style_blending_colour, 0.5),
    item_backing__hover_select__lineColour:                 _canvas_.library.math.blendColours(this.menubar.styleLibrary.default.normal.item_backing__hover_select__lineColour, important_style_blending_colour, 0.5),
    item_backing__hover_select__lineThickness:              0,
    item_backing__hover_select_press__colour:               _canvas_.library.math.blendColours(this.menubar.styleLibrary.default.normal.item_backing__hover_select_press__colour, important_style_blending_colour, 0.5),
    item_backing__hover_select_press__lineColour:           _canvas_.library.math.blendColours(this.menubar.styleLibrary.default.normal.item_backing__hover_select_press__lineColour, important_style_blending_colour, 0.5),
    item_backing__hover_select_press__lineThickness:        0,
    item_backing__hover_glow__colour:                       _canvas_.library.math.blendColours(this.menubar.styleLibrary.default.normal.item_backing__hover_glow__colour, important_style_blending_colour, 0.5),
    item_backing__hover_glow__lineColour:                   _canvas_.library.math.blendColours(this.menubar.styleLibrary.default.normal.item_backing__hover_glow__lineColour, important_style_blending_colour, 0.5),
    item_backing__hover_glow__lineThickness:                0,
    item_backing__hover_glow_press__colour:                 _canvas_.library.math.blendColours(this.menubar.styleLibrary.default.normal.item_backing__hover_glow_press__colour, important_style_blending_colour, 0.5),
    item_backing__hover_glow_press__lineColour:             _canvas_.library.math.blendColours(this.menubar.styleLibrary.default.normal.item_backing__hover_glow_press__lineColour, important_style_blending_colour, 0.5),
    item_backing__hover_glow_press__lineThickness:          0,
    item_backing__hover_glow_select__colour:                _canvas_.library.math.blendColours(this.menubar.styleLibrary.default.normal.item_backing__hover_glow_select__colour, important_style_blending_colour, 0.5),
    item_backing__hover_glow_select__lineColour:            _canvas_.library.math.blendColours(this.menubar.styleLibrary.default.normal.item_backing__hover_glow_select__lineColour, important_style_blending_colour, 0.5),
    item_backing__hover_glow_select__lineThickness:         0,
    item_backing__hover_glow_select_press__colour:          _canvas_.library.math.blendColours(this.menubar.styleLibrary.default.normal.item_backing__hover_glow_select_press__colour, important_style_blending_colour, 0.5),
    item_backing__hover_glow_select_press__lineColour:      _canvas_.library.math.blendColours(this.menubar.styleLibrary.default.normal.item_backing__hover_glow_select_press__lineColour, important_style_blending_colour, 0.5),
    item_backing__hover_glow_select_press__lineThickness:   0,

    checkbox_checkColour:{r:0.7,g:0.7,b:0.7,a:1}, 
};